import type { Metadata } from "next";
import { StarCanvas } from "@/components/star-canvas";
import { Layout } from "@/components/layout";
import Head from "next/head";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://use.typekit.net/arv6uhj.css" />
      </Head>
      <body className="antialiased">
        <StarCanvas />
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
